import { Metadata } from "next";

export const metadata: Metadata = {
  title: "NextJS Template",
  description: "Generated by @zufichris",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={"p-0 m-0 bg-primary"}
      >
     
        {children}
      </body>
    </html>
  );
}
